/**
 * Ingredient Database
 * Stores physical properties of common ingredients for mass estimation.
 * 
 * ⚠️ WARNING: DATA SOURCE DISCLAIMER
 * This database (densities, unit weights, yield, macros) was generated by an LLM (AI).
 * Values have NOT been verified against official food databases (USDA, CIQUAL, etc.).
 * They serve as a temporary Proof of Concept. Treat all values as unverified estimates.
 */



import { loadIngredientDb, buildFastLookupMap } from './ingredients/loader';
import { Ingredient } from './ingredients/schema';

// Re-export Ingredient as IngredientData for backward compatibility
export type IngredientData = Ingredient;

// Load Data (Initial with Core only)
let dbDefinitions = loadIngredientDb();
export let INGREDIENT_DB: Record<string, IngredientData> = buildFastLookupMap(dbDefinitions);

export function configureIngredientDb(sources: Array<{ name: string, data: any }>) {
    dbDefinitions = loadIngredientDb(sources);
    INGREDIENT_DB = buildFastLookupMap(dbDefinitions);
}


import { slugify } from './utils';

export function getIngredientData(name: string): IngredientData | null {
    const slug = slugify(name);
    // Direct match
    if (INGREDIENT_DB[slug]) return INGREDIENT_DB[slug];
    
    // Simple singularization fallback (very naive)
    if (slug.endsWith('s') && INGREDIENT_DB[slug.slice(0, -1)]) {
        return INGREDIENT_DB[slug.slice(0, -1)];
    }

    return null;
}
