#!/usr/bin/env bun
// Generates `src/public/llms-full.txt` — the Gram language spec concatenated into a
// single plain-text file for LLMs/agents to fetch without navigating the site, per
// the llms.txt convention (https://llmstxt.org). Source pages are the single source
// of truth (same files the docs site renders); VitePress `@include` directives are
// resolved inline here so the flattened output never contains a dangling comment.
//
// Must run after scripts/generate-api-fragments.ts, since some pages `@include`
// the fragments it produces (e.g. reference/api/warnings.md).

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const SITE_ORIGIN = "https://gram-lang.org";
const SRC_DIR = join(import.meta.dirname, "..", "src");
const OUT_FILE = join(SRC_DIR, "public", "llms-full.txt");

// [source markdown path relative to src/, site URL path] — the language spec only;
// tutorials, how-to guides, tooling docs, and engine internals stay linked from
// llms.txt instead of inlined here.
const PAGES: [string, string][] = [
	["explanation/philosophy.md", "/explanation/philosophy"],
	[
		"reference/syntax/document-structure.md",
		"/reference/syntax/document-structure",
	],
	["reference/syntax/ingredients.md", "/reference/syntax/ingredients"],
	["reference/syntax/cookware.md", "/reference/syntax/cookware"],
	["reference/syntax/times.md", "/reference/syntax/times"],
	["reference/syntax/temperatures.md", "/reference/syntax/temperatures"],
	[
		"reference/syntax/intermediate-variables.md",
		"/reference/syntax/intermediate-variables",
	],
	[
		"reference/syntax/relative-quantities.md",
		"/reference/syntax/relative-quantities",
	],
	[
		"reference/syntax/composite-ingredients.md",
		"/reference/syntax/composite-ingredients",
	],
	["reference/syntax/cheatsheet.md", "/reference/syntax/cheatsheet"],
	[
		"reference/syntax/ai-generation-notes.md",
		"/reference/syntax/ai-generation-notes",
	],
	["reference/api/data-formats.md", "/reference/api/data-formats"],
	["reference/api/warnings.md", "/reference/api/warnings"],
];

const INCLUDE_RE = /<!--\s*@include:\s*(.+?)\s*-->/g;

function resolveIncludes(content: string, fileDir: string): string {
	return content.replace(INCLUDE_RE, (_match, relPath: string) => {
		const includePath = resolve(fileDir, relPath);
		return readFileSync(includePath, "utf-8").trim();
	});
}

const sections = PAGES.map(([relPath, urlPath]) => {
	const fullPath = join(SRC_DIR, relPath);
	const raw = readFileSync(fullPath, "utf-8");
	const resolved = resolveIncludes(raw, dirname(fullPath)).trim();
	return `<!-- Source: ${SITE_ORIGIN}${urlPath} -->\n\n${resolved}`;
});

const header =
	`<!-- GENERATED by scripts/generate-llms-full.ts — do not edit -->\n` +
	`<!-- The Gram language spec, concatenated for LLM consumption. See also ${SITE_ORIGIN}/llms.txt -->\n\n`;

writeFileSync(OUT_FILE, `${header}${sections.join("\n\n---\n\n")}\n`);

console.log("Generated", OUT_FILE);
