#!/usr/bin/env bun
// Generates the `src/reference/api/parts/{en,fr}/*.md` table fragments included
// (via VitePress `@include`) into the API Reference pages, straight from the
// packages' own source of truth — so the tables can never drift out of sync
// with the code the way hand-written docs can.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
	WarningCode,
	warningTemplates,
	warningSeverity,
} from "@gram-lang/kitchen";
import { ASTNodeType } from "@gram-lang/parser";
import { UNIT_CONVERSIONS } from "@gram-lang/analyzer";
import {
	UNIT_DICTIONARIES,
	TIME_DICTIONARIES,
	getDefaultCategories,
} from "@gram-lang/i18n";

type Locale = "en" | "fr";
const LOCALES: Locale[] = ["en", "fr"];

const OUT_DIR = join(import.meta.dirname, "..", "src/reference/api/parts");

function writeFragment(locale: Locale, name: string, content: string) {
	const dir = join(OUT_DIR, locale);
	mkdirSync(dir, { recursive: true });
	writeFileSync(
		join(dir, name),
		`<!-- GENERATED by scripts/generate-api-fragments.ts — do not edit -->\n\n${content}\n`,
	);
}

function table(headers: string[], rows: string[][]): string {
	const head = `| ${headers.join(" | ")} |`;
	const sep = `| ${headers.map(() => "---").join(" | ")} |`;
	const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
	return `${head}\n${sep}\n${body}`;
}

// Renders each warning's template with a placeholder proxy standing in for
// its payload, so the generated table shows real message shapes (e.g.
// "Variable '{targetName}' not found.") without needing real payload data.
const payloadProxy = new Proxy(
	{},
	{ get: (_t, prop) => `{${String(prop)}}` },
) as never;

// --- warning-codes.md ---------------------------------------------------

const WARNING_LABELS: Record<Locale, string[]> = {
	en: ["Code", "Severity", "Message template"],
	fr: ["Code", "Sévérité", "Modèle de message"],
};

for (const locale of LOCALES) {
	const rows = Object.values(WarningCode).map((code) => [
		`\`${code}\``,
		warningSeverity[code],
		`\`${warningTemplates[code](payloadProxy)}\``,
	]);
	writeFragment(
		locale,
		"warning-codes.md",
		table(WARNING_LABELS[locale], rows),
	);
}

// --- ast-node-types.md ---------------------------------------------------

const AST_LABELS: Record<Locale, string[]> = {
	en: ["Value"],
	fr: ["Valeur"],
};

for (const locale of LOCALES) {
	const rows = Object.values(ASTNodeType).map((v) => [`\`${v}\``]);
	writeFragment(
		locale,
		"ast-node-types.md",
		table(AST_LABELS[locale], rows),
	);
}

// --- units.md --------------------------------------------------------------

const UNITS_LABELS: Record<Locale, string[]> = {
	en: ["Canonical", "Aliases"],
	fr: ["Canonique", "Alias"],
};

for (const locale of LOCALES) {
	const dict = UNIT_DICTIONARIES[locale];
	const rows = Object.entries(dict).map(([canonical, aliases]) => [
		`\`${canonical}\``,
		aliases.map((a) => `\`${a}\``).join(", "),
	]);
	writeFragment(locale, "units.md", table(UNITS_LABELS[locale], rows));
}

// --- time-units.md -----------------------------------------------------

const TIME_LABELS: Record<Locale, string[]> = {
	en: ["Canonical", "Aliases"],
	fr: ["Canonique", "Alias"],
};

for (const locale of LOCALES) {
	const dict = TIME_DICTIONARIES[locale];
	const rows = Object.entries(dict).map(([canonical, aliases]) => [
		`\`${canonical}\``,
		aliases.map((a) => `\`${a}\``).join(", "),
	]);
	writeFragment(locale, "time-units.md", table(TIME_LABELS[locale], rows));
}

// --- unit-conversions.md ------------------------------------------------

const CONVERSIONS_LABELS: Record<Locale, string[]> = {
	en: ["Family", "Unit", "Factor (relative to base)"],
	fr: ["Famille", "Unité", "Facteur (par rapport à la base)"],
};

for (const locale of LOCALES) {
	const rows: string[][] = [];
	for (const [family, def] of Object.entries(UNIT_CONVERSIONS)) {
		for (const [unit, factor] of Object.entries(def.map)) {
			rows.push([
				`\`${family}\` (base: \`${def.base}\`)`,
				`\`${unit}\``,
				String(factor),
			]);
		}
	}
	writeFragment(
		locale,
		"unit-conversions.md",
		table(CONVERSIONS_LABELS[locale], rows),
	);
}

// --- categories.md -------------------------------------------------------

const CATEGORIES_LABELS: Record<Locale, string[]> = {
	en: ["Default categories"],
	fr: ["Catégories par défaut"],
};

for (const locale of LOCALES) {
	const rows = getDefaultCategories(locale).map((c) => [c]);
	writeFragment(
		locale,
		"categories.md",
		table(CATEGORIES_LABELS[locale], rows),
	);
}

console.log("Generated API reference fragments in", OUT_DIR);
