#!/usr/bin/env bun
// Mirrors the root CHANGELOG.md (the single source of truth, generated by
// changesets via generate-release-note.ts) into a Starlight content page, so the
// site never carries a second, hand-maintained copy of the release history.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT_CHANGELOG = join(import.meta.dirname, "..", "..", "..", "CHANGELOG.md");
const OUT_FILE = join(
	import.meta.dirname,
	"..",
	"src",
	"content",
	"docs",
	"docs",
	"changelog.md",
);

const FRONTMATTER = `---
title: Changelog
description: Every release of Gram — new features, fixes, and breaking changes.
---

`;

function main() {
	const source = readFileSync(ROOT_CHANGELOG, "utf-8");
	// Drop the leading "# Changelog" heading: the page's `title` frontmatter
	// already renders as the H1, so keeping it would duplicate the heading.
	const body = source.replace(/^# Changelog\n+/, "");

	writeFileSync(OUT_FILE, FRONTMATTER + body, "utf-8");
	console.log("Synced CHANGELOG.md -> src/content/docs/docs/changelog.md");
}

main();
