#!/usr/bin/env bun
// Copies @astrojs/starlight's own base-token stylesheets (`style/layers.css` and
// `style/props.css`) into src/styles/starlight/. Starlight's Page.astro imports
// these directly by relative path, but neither is in the package's public `exports`
// map, so pages that don't route through Page.astro (this docs site's homepage,
// blog, and playground, which use a custom Layout.astro) can't import them as a
// bare specifier. Vendoring a verbatim copy — regenerated by this script whenever
// @astrojs/starlight is upgraded — gives those pages the exact same complete,
// correctly `@layer`-wrapped token set Starlight pages get, instead of a hand-picked
// subset that silently drifts out of sync (see git history on src/styles/global.css
// for what that looked like).

import { copyFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

const starlightPkgDir = dirname(
	require.resolve("@astrojs/starlight/package.json"),
);
const starlightStyleDir = join(starlightPkgDir, "style");
const destDir = join(import.meta.dirname, "../src/styles/starlight");

mkdirSync(destDir, { recursive: true });

for (const file of ["layers.css", "props.css"]) {
	copyFileSync(join(starlightStyleDir, file), join(destDir, file));
}

console.log("✅ src/styles/starlight/{layers,props}.css vendored");
