// Ingredient database for the playground example recipes (cannelés, empanadas).
// Keys must match slugify() output from @gram-lang/kitchen: lowercase, spaces→dashes, no accents.
// Physical: density in g/ml, unit_weight in g per countable unit.
// Nutrition: values per 100g.
export const DEFAULT_SOURCES = [
	{
		id: "examples",
		name: "Example Recipes",
		data: {
			// --- Shared ---
			flour: {
				name: "Flour",
				aliases: ["wheat flour", "all-purpose flour", "farine"],
				tags: ["wheat", "contains gluten", "vegan"],
				category: "Grains",
				physical: { density: 0.6 },
				nutrition: {
					calories: 364,
					carbs: 76,
					protein: 10,
					fat: 1,
					sugar: 0.3,
					sat_fat: 0.2,
					fiber: 2.7,
					sodium: 2,
				},
			},
			salt: {
				name: "Salt",
				aliases: ["sea salt", "table salt", "sel"],
				tags: ["mineral", "seasoning", "essential"],
				category: "Spices",
				physical: { density: 1.2 },
				nutrition: {
					calories: 0,
					carbs: 0,
					protein: 0,
					fat: 0,
					sugar: 0,
					sat_fat: 0,
					fiber: 0,
					sodium: 38758,
				},
			},
			butter: {
				name: "Butter",
				aliases: ["unsalted butter", "beurre"],
				tags: ["dairy", "fat", "keto", "contains lactose"],
				category: "Dairy",
				physical: { density: 0.91, unit_weight: 227 },
				nutrition: {
					calories: 717,
					carbs: 0.1,
					protein: 0.9,
					fat: 81.1,
					sugar: 0.1,
					sat_fat: 51.4,
					fiber: 0,
					sodium: 11,
				},
			},
			eggs: {
				name: "Eggs",
				aliases: ["egg", "whole eggs", "œuf", "oeufs", "oeuf"],
				tags: ["poultry", "allergen", "protein-rich"],
				category: "Meat",
				physical: { density: 1.05, unit_weight: 50 },
				nutrition: {
					calories: 155,
					carbs: 1.1,
					protein: 13,
					fat: 11,
					sugar: 1.1,
					sat_fat: 3.3,
					fiber: 0,
					sodium: 142,
				},
			},
			water: {
				name: "Water",
				aliases: ["eau"],
				tags: ["liquid", "essential"],
				category: "Beverages",
				physical: { density: 1.0 },
				nutrition: {
					calories: 0,
					carbs: 0,
					protein: 0,
					fat: 0,
					sugar: 0,
					sat_fat: 0,
					fiber: 0,
					sodium: 4,
				},
			},
			oil: {
				name: "Oil",
				aliases: ["vegetable oil", "sunflower oil", "olive oil", "huile"],
				tags: ["fat", "vegan", "gluten-free"],
				category: "Fats",
				physical: { density: 0.92 },
				nutrition: {
					calories: 884,
					carbs: 0,
					protein: 0,
					fat: 100,
					sugar: 0,
					sat_fat: 14,
					fiber: 0,
					sodium: 0,
				},
			},

			// --- Cannelés ---
			sugar: {
				name: "Sugar",
				aliases: ["granulated sugar", "white sugar", "sucre"],
				tags: ["gluten-free", "vegan", "vegetarian"],
				category: "Sugars",
				physical: { density: 0.85 },
				nutrition: {
					calories: 387,
					carbs: 100,
					protein: 0,
					fat: 0,
					sugar: 100,
					sat_fat: 0,
					fiber: 0,
					sodium: 1,
				},
			},
			milk: {
				name: "Milk",
				aliases: ["whole milk", "lait"],
				tags: ["dairy", "contains lactose", "liquid"],
				category: "Dairy",
				physical: { density: 1.03 },
				nutrition: {
					calories: 61,
					carbs: 4.8,
					protein: 3.2,
					fat: 3.3,
					sugar: 5.1,
					sat_fat: 1.9,
					fiber: 0,
					sodium: 43,
				},
			},
			"vanilla-bean": {
				name: "Vanilla Bean",
				aliases: ["vanilla pod", "gousse de vanille"],
				tags: ["spice", "aromatic", "vegan"],
				category: "Spices",
				physical: { density: 0.6, unit_weight: 3 },
				nutrition: {
					calories: 288,
					carbs: 12.6,
					protein: 1.2,
					fat: 0.1,
					sugar: 12.6,
					sat_fat: 0,
					fiber: 0,
					sodium: 0,
				},
			},
			"egg-yolks": {
				name: "Egg Yolks",
				aliases: ["yolk", "egg yolk", "jaune d'oeuf", "jaunes d'oeufs"],
				tags: ["poultry", "allergen", "fat-rich"],
				category: "Meat",
				physical: { density: 1.03, unit_weight: 17 },
				nutrition: {
					calories: 322,
					carbs: 3.6,
					protein: 16,
					fat: 27,
					sugar: 0.6,
					sat_fat: 9.6,
					fiber: 0,
					sodium: 48,
				},
			},
			rum: {
				name: "Rum",
				aliases: ["dark rum", "rhum"],
				tags: ["alcohol", "spirits", "vegan"],
				category: "Beverages",
				physical: { density: 0.94 },
				nutrition: {
					calories: 231,
					carbs: 0,
					protein: 0,
					fat: 0,
					sugar: 0,
					sat_fat: 0,
					fiber: 0,
					sodium: 1,
					alcohol: 11.6,
				},
			},

			// --- Empanadas ---
			onions: {
				name: "Onions",
				aliases: ["onion", "oignon", "oignons"],
				tags: ["vegetable", "aromatic", "vegan"],
				category: "Vegetables",
				physical: { density: 0.45, unit_weight: 110 },
				nutrition: {
					calories: 40,
					carbs: 9.3,
					protein: 1.1,
					fat: 0.1,
					sugar: 4.2,
					sat_fat: 0,
					fiber: 1.7,
					sodium: 4,
				},
			},
			"red-bell-pepper": {
				name: "Red Bell Pepper",
				aliases: ["red pepper", "bell pepper", "poivron rouge"],
				tags: ["vegetable", "fresh", "vegan"],
				category: "Vegetables",
				physical: { density: 0.35, unit_weight: 120 },
				nutrition: {
					calories: 31,
					carbs: 6,
					protein: 1,
					fat: 0.3,
					sugar: 4.2,
					sat_fat: 0,
					fiber: 2.1,
					sodium: 4,
				},
			},
			beef: {
				name: "Beef",
				aliases: ["ground beef", "minced beef", "boeuf haché"],
				tags: ["meat", "protein-rich"],
				category: "Meat",
				physical: { density: 0.9 },
				nutrition: {
					calories: 254,
					carbs: 0,
					protein: 17.2,
					fat: 20,
					sugar: 0,
					sat_fat: 7.6,
					fiber: 0,
					sodium: 66,
				},
			},
			garlic: {
				name: "Garlic",
				aliases: ["ail"],
				tags: ["vegetable", "aromatic", "vegan"],
				category: "Vegetables",
				physical: { density: 0.64, unit_weight: 5 },
				nutrition: {
					calories: 149,
					carbs: 33,
					protein: 6.4,
					fat: 0.5,
					sugar: 1,
					sat_fat: 0.1,
					fiber: 2.1,
					sodium: 17,
				},
			},
			"fresh-oregano": {
				name: "Fresh Oregano",
				aliases: ["oregano", "origan frais"],
				tags: ["herb", "fresh", "vegan"],
				category: "Herbs",
				physical: { density: 0.07 },
				nutrition: {
					calories: 266,
					carbs: 69,
					protein: 9,
					fat: 4.3,
					sugar: 4.1,
					sat_fat: 1.6,
					fiber: 42.5,
					sodium: 25,
				},
			},
			"sweet-paprika": {
				name: "Sweet Paprika",
				aliases: ["paprika", "paprika doux"],
				tags: ["spice", "ground", "vegan"],
				category: "Spices",
				physical: { density: 0.46 },
				nutrition: {
					calories: 282,
					carbs: 54,
					protein: 14,
					fat: 13,
					sugar: 10.3,
					sat_fat: 2.1,
					fiber: 34.9,
					sodium: 68,
				},
			},
			"fresh-parsley": {
				name: "Fresh Parsley",
				aliases: ["parsley", "persil frais"],
				tags: ["herb", "fresh", "vegan"],
				category: "Herbs",
				physical: { density: 0.04 },
				nutrition: {
					calories: 36,
					carbs: 6.3,
					protein: 3,
					fat: 0.8,
					sugar: 0.9,
					sat_fat: 0.1,
					fiber: 3.3,
					sodium: 56,
				},
			},
			"green-olives": {
				name: "Green Olives",
				aliases: ["olives", "olives vertes"],
				tags: ["fruit", "fermented", "vegan"],
				category: "Condiments",
				physical: { density: 0.6, unit_weight: 5 },
				nutrition: {
					calories: 145,
					carbs: 3.8,
					protein: 1,
					fat: 15.3,
					sugar: 0.5,
					sat_fat: 2,
					fiber: 3.3,
					sodium: 1556,
				},
			},
		},
	},
];
