// Shared between astro.config.mjs (Starlight `head` entries) and Layout.astro
// (custom pages: homepage, blog, playground) so the two injection paths never drift apart.

export const UMAMI_WEBSITE_ID = "fa1b1921-1982-4198-bb2b-c30d24f587ce";
export const UMAMI_SCRIPT_SRC = "/script.js";

export const FR_REDIRECT_SCRIPT = `if (typeof window !== "undefined" && (window.location.pathname === "/" || window.location.pathname === "/index.html")) {
  var lang = navigator.language || navigator.userLanguage || "";
  if (lang.toLowerCase().startsWith("fr") && !sessionStorage.getItem("lang_redirected")) {
    sessionStorage.setItem("lang_redirected", "true");
    window.location.replace("/fr/");
  }
}`;

// Covers UI generated by third-party code (Starlight, expressive-code) where we
// can't attach a data-umami-event attribute or an import of trackEvent ourselves.
export const GLOBAL_TRACKING_SCRIPT = `
document.addEventListener('click', function(e) {
  if (!window.umami) return;
  // expressive-code renders the copy button as an unclassed <button> inside a
  // <div class="copy"> within the code block's <figure class="frame">.
  var copyBtn = e.target.closest('.frame .copy button');
  if (copyBtn) {
    window.umami.track('copy-code-block', { page: window.location.pathname });
  }
});

document.addEventListener('change', function(e) {
  if (!window.umami) return;
  // Both our custom LanguageSelect and Starlight's built-in default one (used
  // on /docs/* pages) wrap their <select> in a <starlight-lang-select> element.
  var langSelect = e.target.closest('starlight-lang-select select');
  if (langSelect) {
    var lang = langSelect.value.startsWith('/fr') ? 'fr' : 'en';
    window.umami.track('switch-language', { to: lang });
  }
});

// Starlight's search (Pagefind) renders into #starlight__search via a Svelte
// component we don't own, with no onResults callback exposed. We can't match
// on its "zero results" message text (locale-dependent), but the results
// list (.pagefind-ui__results) is always in the DOM once a search settles,
// empty or not — so an empty list after mutations quiet down means no hits.
document.addEventListener('DOMContentLoaded', function() {
  var searchRoot = document.getElementById('starlight__search');
  if (!searchRoot) return;
  var timer;
  new MutationObserver(function() {
    clearTimeout(timer);
    timer = setTimeout(function() {
      if (!window.umami) return;
      var results = searchRoot.querySelector('.pagefind-ui__results');
      var input = searchRoot.querySelector('.pagefind-ui__search-input');
      if (!results || !input || !input.value) return;
      if (results.children.length === 0) {
        window.umami.track('search-no-results', { query: input.value.slice(0, 200) });
      }
    }, 400);
  }).observe(searchRoot, { childList: true, subtree: true });
});
`;
